#!/bin/bash

runCheck() {
	output=$(phpcs --standard=PSR2 --encoding=utf-8 $dir)
	retval=$?
	if [ $retval -ne 0 ]; then
		echo "$output"
	fi

	exit $retval
}

# skip if travis build check
if [ "$TRAVIS" == "true" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
	dir="src/ phpunit/"
	runCheck
fi

dir=/tmp/phpcs

# get list of files to check
if [ "$TRAVIS" == "true" ]; then
	commit=$TRAVIS_COMMIT
	files=$(git diff --name-only --diff-filter=ACM $commit^1...$commit^2 | grep -e 'php$')
elif [ -n "$GIT_INDEX_FILE" ]; then
	commit="" # should be empty for git pre-commit hook
	files=$(git diff --cached --name-only --diff-filter=ACM | grep -e 'php$')
fi

if [ -z "$files" ]; then
	exit 0
fi

# ensure empty temp directory
if [ -e $dir ]; then
	rm -rf $dir
fi
mkdir -p $dir

# checkout files content to the temporary place
for file in $files; do
	mkdir -p $dir/$(dirname $file)
	git show $commit:$file > $dir/$file
done

# do the check
runCheck
