<?php /** @var $this Verbum\Dict\MainTemplate */
?><!DOCTYPE html>
<html lang="be">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мадэрновы Слоўнік Беларускай Мовы</title>
    <?php foreach ($this->getCSSFilesList() as $file): ?>
        <link href="<?= $file ?>" rel="stylesheet">
    <?php endforeach; ?>
</head>
<body>
    <div class="content">
        <div class="search-form-container">
            <form id="search-form" autocomplete="off">
                <div class="search-button-outer">
                    <button type="submit">Шукаць</button>
                </div>
                <div class="input-outer">
                    <input id="q" type="text" name="q" value="" autofocus="autofocus" />
                    <div id="typeahead" style="display: none;"></div>
                </div>
            </form>
        </div>

        <div id="results" class="results">

        </div>
    </div>

    <script id="template-typeahead" type="text/html">
        <ul>
            {{each suggestions}}
            <li data-value="{{=title}}">{{=title}}</li>
            {{done}}
        </ul>
    </script>

    <script id="template-results" type="text/html">
        {{each articles}}
            <div class="article">
                <p class="title">{{= title}}</p>
                <p data-type="meta">{{= meta}}</p>
                <p>{{= definition}}</p>
                <p><a target="_blank" href="{{= source}}">rv-blr.com</a></p>
            </div>
        {{done}}
    </script>

    <?php foreach ($this->getJSFilesList() as $file) : ?>
        <script src="<?= $file ?>"></script>
    <?php endforeach; ?>

    <script type="text/javascript">
        App.start();
    </script>
</body>
</html>
