<?php /** @var $this Verbum\Dict\MainTemplate */
?><!DOCTYPE html>
<html lang="be">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мадэрновы Слоўнік Беларускай Мовы</title>
    <?php foreach ($this->getCSSFilesList() as $file): ?>
        <link href="<?= $file ?>" rel="stylesheet">
    <?php endforeach; ?>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" style="padding:5px;">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Слоўнік</a>
            </div>

            <form class="navbar-form" role="search">
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputEmail3" placeholder="Text text..." style="width:100%">
                </div>
                <button type="submit" class="btn btn-default ">Пошук</button>
            </form>
        </div>
    </nav>

    <div class="container">
        <div class="starter-template" style="text-align: center;">
            <h1>Мадэрновы Слоўнік Беларускай Мовы</h1>
            <blockquote class="blockquote-reverse">
            <p class="lead">Мова...<br/>
                Родная мова<br/>
                У марах, у песнях, у снах.<br/>
                Мае ў ёй кожнае слова<br/>
                Свой колер, і смак, і пах.<br/>
                Зліваюцца гукі ў словы<br/>
                I ў рэчышча роднай мовы,<br/>
                Як рэкі ў мора, цякуць,<br/>
                I думкі мае плывуць<br/>
                На хвалях і дзён, і начэй<br/>
                Да сэрцаў людскіх і вачэй.</p>
                <footer>Анатоль Грачанікаў, <cite title="Source Title">Мова...</cite></footer>
            </blockquote>
        </div>

    </div>

    <script type="text/template" id="search-panel-template">
        <input type="text" name="q" value=""> <button>Search</button>
    </script>

    <?php foreach ($this->getJSFilesList() as $file) : ?>
        <script src="<?= $file ?>"></script>
    <?php endforeach; ?>

    <script type="text/javascript">
        App.start();
    </script>
</body>
</html>
