<?php /** @var $this Verbum\Dict\MainTemplate */
?><!DOCTYPE html>
<html lang="be">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мадэрновы Слоўнік Беларускай Мовы</title>
    <?php foreach ($this->getCSSFilesList() as $file): ?>
        <link href="<?= $file ?>" rel="stylesheet">
    <?php endforeach; ?>
</head>
<body>

    <div class="content">
        <div class="search-form-container">
            <form id="search-form" autocomplete="off" onsubmit="return false;">
                <input id="q" type="text" name="q" value="sdfsd" autofocus="autofocus" />
            </form>
        </div>

        <div class="results">
            <div class="article">
                <p class="title">
                    Пананосіць (пананошваць)
                </p>
                <p>дзеяслоў | закончанае трыванне</p>
                <p>1. чаго. Прынесці за некалькі прыёмаў многа чаго-н. П. дроў да печы. 2. чаго. Сваім рухам нанесці многа чаго-н., утварыць што-н. Вецер пананосіў лісця ў сенцы. З. што і чаго. Нанесці на паперу, карту, схему ўсё, многае. П. населеныя пункты на карту.</p>
                <p>Крыніца: <a target="_blank" href="http://rv-blr.com/slounik.jsp?letterId=0&maskId=0&pageId=2130">rv-blr.com</a></p>
            </div>
            <div class="article">
                <p class="title">
                    Пананосіць (пананошваць)
                </p>
                <p>дзеяслоў | закончанае трыванне</p>
                <p>1. чаго. Прынесці за некалькі прыёмаў многа чаго-н. П. дроў да печы. 2. чаго. Сваім рухам нанесці многа чаго-н., утварыць што-н. Вецер пананосіў лісця ў сенцы. З. што і чаго. Нанесці на паперу, карту, схему ўсё, многае. П. населеныя пункты на карту.</p>
                <p>Крыніца: <a target="_blank" href="http://rv-blr.com/slounik.jsp?letterId=0&maskId=0&pageId=2130">rv-blr.com</a></p>
            </div>
        </div>
    </div>

    <script type="text/x-handlebars-template" id="hbt">
        ololo <div>ol123</div> lolol
    </script>

    <?php foreach ($this->getJSFilesList() as $file) : ?>
        <script src="<?= $file ?>"></script>
    <?php endforeach; ?>

    <script type="text/javascript">
        App.start();
    </script>
</body>
</html>
